//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string UserID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public string BuyerID { get; set; }
        public Nullable<int> CartId { get; set; }
    
        public virtual Cart Cart { get; set; }
    }
}
