//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.UserBuyingProducts = new HashSet<UserBuyingProduct>();
        }
    
        public int ProductID { get; set; }
        public string SellerID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string UoM { get; set; }
        public int Quanlity { get; set; }
        public Nullable<int> Price { get; set; }
        public bool Enable { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBuyingProduct> UserBuyingProducts { get; set; }
    }
}
